"""add category

Revision ID: d5411bf13a2f
Revises: 86382d72e645
Create Date: 2025-06-24 10:44:33.505832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5411bf13a2f'
down_revision: Union[str, None] = '86382d72e645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('categories_id_idx'), 'categories', ['id'], unique=False)
    op.add_column('dares', sa.Column('category_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('dares_category_id_fkey'), 'dares', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('truths', sa.Column('category_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(op.f('truths_category_id_fkey'), 'truths', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('truths_category_id_fkey'), 'truths', type_='foreignkey')
    op.drop_column('truths', 'category_id')
    op.drop_constraint(op.f('dares_category_id_fkey'), 'dares', type_='foreignkey')
    op.drop_column('dares', 'category_id')
    op.drop_index(op.f('categories_id_idx'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
